const OIC_ROLES = [
  "PROGRAMMER",
  "ANALYST CUM PROGRAMMER",
  "ADDITIONAL DIRECTOR",
  "SYSTEM ANALYST",
  "SECRETARY OF I.T.",
  "COMMISSIONER OF I.T.",
  "TECHNICAL DIRECTOR",
];
 
module.exports = { OIC_ROLES };